import AuthForm from "../../components/auth-form/AuthForm";
import Head from "next/head";

const AuthPage = () => {
    return (
        <div>
            <Head>
                <title>Log In</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AuthForm />
        </div>
    );
};

export default AuthPage