import Head from 'next/head'
import Homepage from "../components/homepage/Homepage";

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Homepage />
    </div>
  )
}

export default HomePage;